name: user-statistician

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  stats:
    runs-on: ubuntu-latest
      
    steps:
    - uses: actions/checkout@v4

    - name: Generate the user stats image
      uses: cicirello/user-statistician@v1
      with:
        image-file: images/userstats.svg
        custom-title: My GitHub Statistics
        max-languages: 100
      env:
        GITHUB_TOKEN: ${{secrets.TOKEN}}
